---
output:
  md_document:
    variant: markdown_github
always_allow_html: yes
---

<!-- NEWS.md is generated from NEWS.Rmd. Please edit that file -->

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

## otsad 0.2.0

* New Features
    + `EORELM-AD` R6 class that implements our ensemble-based online recurrent extreme learning machine anomaly detector (EORELM-AD).
    + `DinamycNormalizer` R6 class that implements the unsupervised dynamic z-score standardization proposed by Bollegala.
    + `WindowNormalizer` R6 class allows normalizing the data set in an online manner one-by-one or chunk-by-chunk.
    + `AdaptiveNormalizer` R6 class with our adaptation of the method proposed by Ogasawara et al. for one-pass online time-series adaptive normalization.
    + `AdaptiveNormalizer2` R6 class that implements our adaptation to one-pass online processing of the adaptive normalization method proposed by Gupta and Hewett.
    + `AnomalyLikelihoodScorer` R6 class that implements the anomaly likelihood introduced by Ahmad et al.
    + `DynamicThresholdScorer` R6 class that implements the online anomaly scoring method (based on the prediction errors) proposed by Buda et al.
    + `SigmaScorer` R6 class that allows computing the anomaly score online based on historical prediction errors and 3-sigma control limits.
    + `DynamicSigmaScorer` R6 class that allows computing the anomaly score online based on the prediction errors and 3-sigma control limits.

